<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.example.org/model" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="SPEObject" eSuperTypes="#//IHasOperation #//IHasMatchTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="this" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//SPEAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outboundLinks" upperBound="-1"
        eType="#//SPELink" eOpposite="#//SPELink/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inboundLinks" upperBound="-1"
        eType="#//SPELink" eOpposite="#//SPELink/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPEAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="== value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPELink" eSuperTypes="#//IHasOperation #//IHasMatchTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="has"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//SPEObject"
        eOpposite="#//SPEObject/outboundLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//SPEObject"
        eOpposite="#//SPEObject/inboundLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SPEGroup" eSuperTypes="#//IHasOperation #//IHasMatchTag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//SPEObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//SPELink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subGroups" upperBound="-1"
        eType="#//SPEGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MatchTag">
    <eLiterals name="Default"/>
    <eLiterals name="Not" value="1"/>
    <eLiterals name="Optional" value="3" literal="Optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operations">
    <eLiterals name="Nop"/>
    <eLiterals name="Create" value="1"/>
    <eLiterals name="Delete" value="3" literal="Delete"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IHasMatchTag" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="#//MatchTag"
        defaultValueLiteral="Default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IHasOperation" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//Operations"
        defaultValueLiteral="Nop"/>
  </eClassifiers>
</ecore:EPackage>
